require File.expand_path( File.dirname(__FILE__) + '/../spec_helper' )

# contains shared behavior that we need.
require File.expand_path( File.dirname(__FILE__) + '/../transmem_spec_shared' )

require 'transmem/toppred'
require 'yaml'

describe TopPred::Index do
  before(:all) do
    @toppred_file = Tfiles + '/toppred.small.out'
    @obj = TopPred::Index.new(@toppred_file)
    @test_hash = {"YAL001C"=>0, "YAL011W"=>0, "YAL009W"=>2, "YAL010C"=>1, "YAL008W"=>3, "YAL007C"=>2, "YAL004W"=>0, "YAL005C"=>1, "YAL003W"=>0, "YAL002W"=>3, "YAL013W"=>0, "YAL014C"=>1, "YAL012W"=>1}
    @ref_to_key= { 'gi|16127905|ref|NP_414542.1| thr operon leader peptide [Escherichia coli K12]' => 'gi_16127905_ref_NP_414542_1_',
      'SWN:PWP1_HUMAN PERIODIC TRYPTOPHAN PROTEIN 1 HOMOLOG' => 'SWN_PWP1_HUMAN',
      'MY:B|/-"[super]"duper!@#$%^&*(wil) and other stuff' => 'MY_B_____super__duper_________wil_' }
  end
  it_should_behave_like 'a transmem index'
end

describe "a toppred parser", :shared => true do
  it 'parses a toppred file into a hash structure' do
    @file_to_hash.exist_as_a_file?.should be_true
    hash = @class.default_index(@file_to_hash)
    hash.should == @structure_to_create
  end
end

describe "TopPred parsing a text file" do
  before(:all) do
    @class = TopPred
    @file_to_hash = Tfiles + '/toppred.small.out'
    @structure_to_create = YAML.load(TopPredSupportingFile::MY_YAML1)
    @structure_to_create.each {|id,hash| string_to_symbol(hash) }
  end
  it_should_behave_like 'a toppred parser'
end

describe "TopPred parsing an xml file" do
  before(:all) do
    @class = TopPred
    @file_to_hash = Tfiles + '/toppred.xml.out'
    @structure_to_create = YAML.load(TopPredSupportingFile::MY_YAML2)
    @structure_to_create.each {|id,hash| string_to_symbol(hash) }
  end
  it_should_behave_like 'a toppred parser'
end

describe TopPred::Index do
  before(:all) do
    toppred_file = Tfiles + '/toppred.xml.out'
    @obj = TopPred::Index.new(toppred_file)
    @tm_test = {
      :mykey => 'SWN_K1CL_HUMAN',
      :seqs => %w(GFG VGSGYGGSAFGFG GGGSL),
      :exps => 
      {
        :number => [2.0, 7.0, 3.0],
        :fraction => [2.0/3, 7.0/13, 3.0/5 ],
      }
    }
  end
  it_should_behave_like "a calculator of transmembrane overlap"
end


module TopPredSupportingFile
  MY_YAML1 = <<END
--- 
YAL011W: 
  aaseq: MPAVLRTRSKESSIEQKPASRTRTRSRRGKRGRDDDDDDDDEESDDAYDEVGNDYDEYASRAKLATNRPFEIVAGLPASVELPNYNSSLTHPQSIKNSGVLYDSLVSSRRTWVQGEMFELYWRRPKKIVSESTPAATESPTSGTIPLIRDKMQKMCDCVMSGGPHTFKVRLFILKNDKIEQKWQDEQELKKKEKELKRKNDAEAKRLRMEERKRQQMQKKIAKEQKLQLQKENKAKQKLEQEALKLKRKEEMKKLKEQNKNKQGSPSSSMHDPRMIMNLNLMAQEDPKLNTLMETVAKGLANNSQLEEFKKFIEIAKKRSLEENPVNKRPSVTTTRPAPPSKAKDVAEDHRLNSITLVKSSKTAATEPEPKKADDENAEKQQSKEAKTTAESTQVDVKKEEEDVKEKGVKSEDTQKKEDNQVVPKRKRRKNAIKEDKDMQLTAFQQKYVQGAEIILEYLEFTHSRYYLPKKSVVEFLEDTDEIIISWIVIHNSKEIEKFKTKKIKAKLKADQKLNKEDAKPGSDVEKEVSFNPLFEADCPTPLYTPMTMKLSGIHKRFNQIIRNSVSPMEEVVKEMEKILQIGTRLSGYNLWYQLDGYDDEALSESLRFELNEWEHAMRSRRHKR
  num_found: 0
YAL001C: 
  aaseq: MVLTIYPDELVQIVSDKIASNKGKITLNQLWDISGKYFDLSDKKVKQFVLSCVILKKDIEVYCDGAITTKNVTDIIGDANHSYSVGITEDSLWTLLTGYTKKESTIGNSAFELLLEVAKSGEKGINTMDLAQVTGQDPRSVTGRIKKINHLLTSSQLIYKGHVVKQLKLKKFSHDGVDSNPYINIRDHLATIVEVVKRSKNGIRQIIDLKRELKFDKEKRLSKAFIAAIAWLDEKEYLKKVLVVSPKNPAIKIRCVKYVKDIPDSKGSPSFEYDSNSADEDSVSDSKAAFEDEDLVEGLDNFNATDLLQNQGLVMEEKEDAVKNEVLLNRFYPLQNQTYDIADKSGLKGISTMDVVNRITGKEFQRAFTKSSEYYLESVDKQKENTGGYRLFRIYDFEGKKKFFRLFTAQNFQKLTNAEDEISVPKGFDELGKSRTDLKTLNEDNFVALNNTVRFTTDSDGQDIFFWHGELKIPPNSKKTPNKNKRKRQVKNSTNASVAGNISNPKRIKLEQHVSTAQEPKSAEDSPSSNGGTVVKGKVVNFGGFSARSLRSLQRQRAILKVMNTIGGVAYLREQFYESVSKYMGSTTTLDKKTVRGDVDLMVESEKLGARTEPVSGRKIIFLPTVGEDAIQRYILKEKDSKKATFTDVIHDTEIYFFDQTEKNRFHRGKKSVERIRKFQNRQKNAKIKASDDAISKKSTSVNVSDGKIKRRDKKVSAGRTTVVVENTKEDKTVYHAGTKDGVQALIRAVVVTKSIKNEIMWDKITKLFPNNSLDNLKKKWTARRVRMGHSGWRAYVDKWKKMLVLAIKSEKISLRDVEELDLIKLLDIWTSFDEKEIKRPLFLYKNYEENRKKFTLVRDDTLTHSGNDLAMSSMIQREISSLKKTYTRKISASTKDLSKSQSDDYIRTVIRSILIESPSTTRNEIEALKNVGNESIDNVIMDMAKEKQIYLHGSKLECTDTLPDILENRGNYKDFGVAFQYRCKVNELLEAGNAIVINQEPSDISSWVLIDLISGELLNMDVIPMVRNVRPLTYTSRRFEIRTLTPPLIIYANSQTKLNTARKSAVKVPLGKPFSRLWVNGSGSIRPNIWKQVVTMVVNEIIFHPGITLSRLQSRCREVLSLHEISEICKWLLERQVLITTDFDGYWVNHNWYSIYEST
  num_found: 0
YAL010C: 
  num_putative_transmembrane_segments: 1
  aaseq: MLPYMDQVLRAFYQSTHWSTQNSYEDITATSRTLLDFRIPSAIHLQISNKSTPNTFNSLDFSTRSRINGSLSYLYSDAQQLEKFMRNSTDIPLQDATETYRQLQPNLNFSVSSANTLSSDNTTVDNDKKLLHDSKFVKKSLYYGRMYYPSSDLEAMIIKRLSPQTQFMLKGVSSFKESLNVLTCYFQRDSHRNLQEWIFSTSDLLCGYRVLHNFLTTPSKFNTSLYNNSSLSLGAEFWLGLVSLSPGCSTTLRYYTHSTNTGRPLTLTLSWQPLFGHISSTYSAKTGTNSTFCAKYDFNLYSIESNLSFGCEFWQKKHHLLETNKNNNDKLEPISDELVDINPNSRATKLLHENVPDLNSAVNDIPSTLDIPVHKQKLLNDLTYAFSSSLRKIDEERSTIEKFDNKINSSIFTSVWKLSTSLRDKTLKLLWEGKWRGFLISAGTELVFTRGFQESLSDDEKNDNAISISATDTENGNIPVFPAKFGIQFQYST
  best_structure_probability: 1.0
  transmembrane_segments: 
  - aaseq: SLGAEFWLGLVSLSPGCSTTL
    stop: 252
    start: 232
    probability: 1.0
  num_certain_transmembrane_segments: 1
  num_found: 2
YAL009W: 
  num_putative_transmembrane_segments: 0
  aaseq: MEPESIGDVGNHAQDDSASIVSGPRRRSTSKTSSAKNIRNSSNISPASMIFRNLLILEDDLRRQAHEQKILKWQFTLFLASMAGVGAFTFYELYFTSDYVKGLHRVILQFTLSFISITVVLFHISGQYRRTIVIPRRFFTSTNKGIRQFNVKLVKVQSTWDEKYTDSVRFVSRTIAYCNIYCLKKFLWLKDDNAIVKFWKSVTIQSQPRIGAVDVKLVLNPRAFSAEIREGWEIYRDEFWAREGARRRKQAHELRPKSE
  best_structure_probability: 1.0
  transmembrane_segments: 
  - aaseq: WQFTLFLASMAGVGAFTFYEL
    stop: 93
    start: 73
    probability: 1.0
  - aaseq: VILQFTLSFISITVVLFHISG
    stop: 126
    start: 106
    probability: 1.0
  num_certain_transmembrane_segments: 2
  num_found: 2
YAL008W: 
  num_putative_transmembrane_segments: 0
  aaseq: MTLAFNMQRLVFRNLNVGKRMFKNVPLWRFNVANKLGKPLTRSVGLGGAGIVAGGFYLMNRQPSKLIFNDSLGAAVKQQGPLEPTVGNSTAITEERRNKISSHKQMFLGSLFGVVLGVTVAKISILFMYVGITSMLLCEWLRYKGWIRINLKNIKSVIVLKDVDLKKLLIDGLLGTEYMGFKVFFTLSFVLASLNANK
  best_structure_probability: 1.0
  transmembrane_segments: 
  - aaseq: LTRSVGLGGAGIVAGGFYLMN
    stop: 60
    start: 40
    probability: 1.0
  - aaseq: AKISILFMYVGITSMLLCEWL
    stop: 141
    start: 121
    probability: 1.0
  - aaseq: TEYMGFKVFFTLSFVLASLNA
    stop: 196
    start: 176
    probability: 1.0
  num_certain_transmembrane_segments: 3
  num_found: 3
YAL007C: 
  num_putative_transmembrane_segments: 0
  aaseq: MIKSTIALPSFFIVLILALVNSVAASSSYAPVAISLPAFSKECLYYDMVTEDDSLAVGYQVLTGGNFEIDFDITAPDGSVITSEKQKKYSDFLLKSFGVGKYTFCFSNNYGTALKKVEITLEKEKTLTDEHEADVNNDDIIANNAVEEIDRNLNKITKTLNYLRAREWRNMSTVNSTESRLTWLSILIIIIIAVISIAQVLLIQFLFTGRQKNYV
  best_structure_probability: 1.0
  transmembrane_segments: 
  - aaseq: STIALPSFFIVLILALVNSVA
    stop: 24
    start: 4
    probability: 1.0
  - aaseq: LTWLSILIIIIIAVISIAQVL
    stop: 201
    start: 181
    probability: 1.0
  num_certain_transmembrane_segments: 2
  num_found: 2
YAL005C: 
  num_putative_transmembrane_segments: 1
  aaseq: MSKAVGIDLGTTYSCVAHFANDRVDIIANDQGNRTTPSFVAFTDTERLIGDAAKNQAAMNPSNTVFDAKRLIGRNFNDPEVQADMKHFPFKLIDVDGKPQIQVEFKGETKNFTPEQISSMVLGKMKETAESYLGAKVNDAVVTVPAYFNDSQRQATKDAGTIAGLNVLRIINEPTAAAIAYGLDKKGKEEHVLIFDLGGGTFDVSLLFIEDGIFEVKATAGDTHLGGEDFDNRLVNHFIQEFKRKNKKDLSTNQRALRRLRTACERAKRTLSSSAQTSVEIDSLFEGIDFYTSITRARFEELCADLFRSTLDPVEKVLRDAKLDKSQVDEIVLVGGSTRIPKVQKLVTDYFNGKEPNRSINPDEAVAYGAAVQAAILTGDESSKTQDLLLLDVAPLSLGIETAGGVMTKLIPRNSTISTKKFEIFSTYADNQPGVLIQVFEGERAKTKDNNLLGKFELSGIPPAPRGVPQIEVTFDVDSNGILNVSAVEKGTGKSNKITITNDKGRLSKEDIEKMVAEAEKFKEEDEKESQRIASKNQLESIAYSLKNTISEAGDKLEQADKDTVTKKAEETISWLDSNTTASKEEFDDKLKELQDIANPIMSKLYQAGGAPGGAAGGAPGGFPGGAPPAPEAEGPTVEEVD
  best_structure_probability: 1.0
  transmembrane_segments: 
  - aaseq: AGGAPGGAAGGAPGGFPGGAP
    stop: 628
    start: 608
    probability: 1.0
  num_certain_transmembrane_segments: 1
  num_found: 2
YAL004W: 
  num_putative_transmembrane_segments: 1
  aaseq: MGVTSGGLNFKDTVFNEQQRDIESTTTQVENQDVFFLTLLVQTVSNGSGGRFVNNTQDIQTSNGTSILGSLSLRIVEVSWDSDDSVIDLGSQVRFGSFLHLTQDHGGDLFWGKVLGFTLKFNLNLRLTVNIDQLEWEVLHVSLHFWVVEVSTDQTLSVENGIRRIHSSLILSSITNQSFSVSESDKRWSGSVTLIVGNNVHTIISKVSNTRVCCT
  best_structure_probability: 0.06
  transmembrane_segments: 
  - aaseq: QDVFFLTLLVQTVSNGSGGRF
    stop: 52
    start: 32
    probability: 0.06
  num_certain_transmembrane_segments: 0
  num_found: 1
YAL003W: 
  aaseq: MASTDFSKIETLKQLNASLADKSYIEGTAVSQADVTVFKAFQSAYPEFSRWFNHIASKADEFDSFPAASAAAAEEEEDDDVDLFGSDDEEADAEAEKLKAERIAAYNAKKAAKPAKPAAKSIVTLDVKPWDDETNLEEMVANVKAIEMEGLTWGAHQFIPIGFGIKKLQINCVVEDDKVSLDDLQQSIEEDEDHVQSTDIAAMQKL
  num_found: 0
YAL014C: 
  num_putative_transmembrane_segments: 0
  aaseq: MDVLKLGYELDQLSDLVEERTRLVSVLKLAPTSNDNVTLKRQLGSILELLQKCAPNDELISRYNTILDKIPDTAVDKELYRFQQQVARNTDEVSKESLKKVRFKNDDELTVMYKDDDEQDEESPLPSTHTPYKDEPLQSQLQSQSQPQPPQPMVSNQELFINQQQQLLEQDSHLGALSQSIGRTHDISLDLNNEIVSQNDSLLVDLENLIDNNGRNLNRASRSMHGFNNSRFKDNGNCVIILVLIVVLLLLLLVL
  best_structure_probability: 1.0
  transmembrane_segments: 
  - aaseq: NGNCVIILVLIVVLLLLLLVL
    stop: 255
    start: 235
    probability: 1.0
  num_certain_transmembrane_segments: 1
  num_found: 1
YAL013W: 
  num_putative_transmembrane_segments: 1
  aaseq: MSQQTPQESEQTTAKEQDLDQESVLSNIDFNTDLNHNLNLSEYCISSDAGTEKMDSDEEKSLANLPELKYAPKLSSLVKQETLTESLKRPHEDEKEAIDEAKKMKVPGENEDESKEEEKSQELEEAIDSKEKSTDARDEQGDEGDNEEENNEEDNENENEHTAPPALVMPSPIEMEEQRMTALKEITDIEYKFAQLRQKLYDNQLVRLQTELQMCLEGSHPELQVYYSKIAAIRDYKLHRAYQRQKYELSCINTETIATRTFIHQDFHKKVTDLRARLLNRTTQTWYDINKERRDMDIVIPDVNYHVPIKLDNKTLSCITGYASAAQLCYPGEPVAEDLACESIEYRYRANPVDKLEVIVDRMRLNNEISDLEGLRKYFHSFPGAPELNPLRDSEINDDFHQWAQCDRHTGPHTTSFCYS
  best_structure_probability: 0.08
  transmembrane_segments: 
  - aaseq: KTLSCITGYASAAQLCYPGEP
    stop: 334
    start: 314
    probability: 0.08
  num_certain_transmembrane_segments: 0
  num_found: 1
YAL002W: 
  num_putative_transmembrane_segments: 2
  aaseq: MEQNGLDHDSRSSIDTTINDTQKTFLEFRSYTQLSEKLASSSSYTAPPLNEDGPKGVASAVSQGSESVVSWTTLTHVYSILGAYGGPTCLYPTATYFLMGTSKGCVLIFNYNEHLQTILVPTLSEDPSIHSIRSPVKSIVICSDGTHVAASYETGNICIWNLNVGYRVKPTSEPTNGMTPTPALPAVLHIDDHVNKEITGLDFFGARHTALIVSDRTGKVSLYNGYRRGFWQLVYNSKKILDVNSSKEKLIRSKLSPLISREKISTNLLSVLTTTHFALILLSPHVSLMFQETVEPSVQNSLVVNSSISWTQNCSRVAYSVNNKISVISISSSDFNVQSASHSPEFAESILSIQWIDQLLLGVLTISHQFLVLHPQHDFKILLRLDFLIHDLMIPPNKYFVISRRSFYLLTNYSFKIGKFVSWSDITLRHILKGDYLGALEFIESLLQPYCPLANLLKLDNNTEERTKQLMEPFYNLSLAALRFLIKKDNADYNRVYQLLMVVVRVLQQSSKKLDSIPSLDVFLEQGLEFFELKDNAVYFEVVANIVAQGSVTSISPVLFRSIIDYYAKEENLKVIEDLIIMLNPTTLDVDLAVKLCQKYNLFDLLIYIWNKIFDDYQTPVVDLIYRISNQSEKCVIFNGPQVPPETTIFDYVTYILTGRQYPQNLSISPSDKCSKIQRELSAFIFSGFSIKWPSNSNHKLYICENPEEEPAFPYFHLLLKSNPSRFLAMLNEVFEASLFNDDNDMVASVGEAELVSRQYVIDLLLDAMKDTGNSDNIRVLVAIFIATSISKYPQFIKVSNQALDCVVNTICSSRVQGIYEISQIALESLLPYYHSRTTENFILELKEKNFNKVLFHIYKSENKYASALSLILETKDIEKEYNTDIVSITDYILKKCPPGSLECGKVTEVIETNFDLLLSRIGIEKCVTIFSDFDYNLHQEILEVKNEETQQKYLDKLFSTPNINNKVDKRLRNLHIELNCKYKSKREMILWLNGTVLSNAESLQILDLLNQDSNFEAAAIIHERLESFNLAVRDLLSFIEQCLNEGKTNISTLLESLRRAFDDCNSAGTEKKSCWILLITFLITLYGKYPSHDERKDLCNKLLQEAFLGLVRSKSSSQKDSGGEFWEIMSSVLEHQDVILMKVQDLKQLLLNVFNTYKLERSLSELIQKIIEDSSQDLVQQYRKFLSEGWSIHTDDCEICGKKIWGAGLDPLLFLAWENVQRHQDMISVDLKTPLVIFKCHHGFHQTCLENLAQKPDEYSCLICQTESNPKIV
  best_structure_probability: 1.0
  transmembrane_segments: 
  - aaseq: GAYGGPTCLYPTATYFLMGTS
    stop: 102
    start: 82
    probability: 1.0
  - aaseq: TNLLSVLTTTHFALILLSPHV
    stop: 286
    start: 266
    probability: 1.0
  - aaseq: KKSCWILLITFLITLYGKYPS
    stop: 1092
    start: 1072
    probability: 1.0
  num_certain_transmembrane_segments: 3
  num_found: 5
YAL012W: 
  num_putative_transmembrane_segments: 0
  aaseq: MTLQESDKFATKAIHAGEHVDVHGSVIEPISLSTTFKQSSPANPIGTYEYSRSQNPNRENLERAVAALENAQYGLAFSSGSATTATILQSLPQGSHAVSIGDVYGGTHRYFTKVANAHGVETSFTNDLLNDLPQLIKENTKLVWIETPTNPTLKVTDIQKVADLIKKHAAGQDVILVVDNTFLSPYISNPLNFGADIVVHSATKYINGHSDVVLGVLATNNKPLYERLQFLQNAIGAIPSPFDAWLTHRGLKTLHLRVRQAALSANKIAEFLAADKENVVAVNYPGLKTHPNYDVVLKQHRDALGGGMISFRIKGGAEAASKFASSTRLFTLAESLGGIESLLEVPAVMTHGGIPKEAREASGVFDDLVRISVGIEDTDDLLEDIKQALKQATN
  best_structure_probability: 1.0
  transmembrane_segments: 
  - aaseq: QYGLAFSSGSATTATILQSLP
    stop: 92
    start: 72
    probability: 1.0
  num_certain_transmembrane_segments: 1
  num_found: 1
END

MY_YAML2 = <<END_YAML2
--- 
SWN_SM33_HUMAN: 
  aaseq: MSDQEAKPSTEDLGDKKEGEYIKLKVIGQDSSEIHFKVKMTTHLKKLKESYCQRQGVPMNSLRFLFEGQRIADNHTPKELGMEEEDVIEVYQEQTGGHSTV
  num_found: 0
SWN_UBP3_HUMAN: 
  num_putative_transmembrane_segments: 1
  transmembrane_segments: 
  - aaseq: TMPGYGGAASAGASVFGASGL
    stop: 724
    start: 704
    probability: 21.0
  - aaseq: YELFAFISHMGTSTMSGHYIC
    stop: 826
    start: 806
    probability: 21.0
  aaseq: MQRRGALFGMPGGSGGRKMAAGDIGELLVPHMPTIRVPRSGDRVYKNECAFSYDSPNSEGGLYVCMNTFLAFGREHVERHFRKTGQSVYMHLKRHAREKVRGASGGALPKRRNSKIFLDLDTDDDLNSDDYEYEDEAKLVIFPDHYEIALPNIEELPALVTIACDAVLSSKSPYRKQDPDTWENELPVSKYANNLTQLDNGVRIPPSGWKCARCDLRENLWLNLTDGSVLCGKWFFDSSGGNGHALEHYRDMGYPLAVKLGTITPDGADVYSFQEEEPVLDPHLAKHLAHFGIDMLHMHGTENGLQDNDIKLRVSEWEVIQESGTKLKPMYGPGYTGLKNLGNSCYLSSVMQAIFSIPEFQRAYVGNLPRIFDYSPLDPTQDFNTQMTKLGHGLLSGQYSKPPVKSELIEQVMKEEHKPQQNGISPRMFKAFVSKSHPEFSSNRQQDAQEFFLHLVNLVERNRIGSENPSDVFRFLVEERIQCCQTRKVRYTERVDYLMQLPVAMEAATNKDELIAYELTRREAEANRRPLPELVRAKIPFSACLQAFSEPENVDDFWSSALQAKSAGVKTSRFASFPEYLVVQIKKFTFGLDWVPKKFDVSIDMPDLLDINHLRARGLQPGEEELPDISPPIVIPDDSKDRLMNQLIDPSDIDESSVMQLAEMGFPLEACRKAVYFTGNMGAEVAFNWIIVHMEEPDFAEPLTMPGYGGAASAGASVFGASGLDNQPPEEIVAIITSMGFQRNQAIQALRATNNNLERALDWIFSHPEFEEDSDFVIEMENNANANIISEAKPEGPRVKDGSGTYELFAFISHMGTSTMSGHYICHIKKEGRWVIYNDHKVCASERPPKDLGYMYFYRRIPS
  num_certain_transmembrane_segments: 2
  num_found: 3
SWN_UBPN_HUMAN: 
  num_putative_transmembrane_segments: 3
  transmembrane_segments: 
  - aaseq: PSSTSSASALYGQPLLLSVPK
    stop: 556
    start: 536
    probability: 21.0
  aaseq: MYNVGEHNLFPGPIDNSGLFSDPESQTLKEHLIDELDYVLVPTEAWNKLLNWYGCVEGQQPIVRKVVEHGLFVKHCKVEVYLLELKLCENSDPTNVLSCHFSKADTIATIEKEMRKLFNIPAERETRLWNKYMSNTYEQLSKLDNTVQDAGLYQGQVLVIEPQNEDGTWPRQTLQSKSSTAPSRNFTTSPKSSASPYSSVSASLIANGDSTSTCGMHSSGVSRGGSGFSASYNCQEPPSSHIQPGLCGLGNLGNTCFMNSALQCLSNTHPLTDYFLKDEYEAEINRDNPLGMKGEIAEAYAELIKQMWSGRDAHVAPWMFKTQVGRFAPQFSGYQQQDSQELLAFPSRWIHEDLNRVKKKPYLELKDANGRPDAVVAKEAWENHRLRNDSVIVDTFHGLFKSTLVCPECAKVSVTFDPFCYLTLPLPLKKDRVMEVFLVPADPHCRPTQYRVTVPLMGAVSDLCEALSRLSGIAAENMVVADVYNHRFHKIFQMDEGLNHIMPRDDIFVYEVCSTSVDGSECVTLPVYFRERKSRPSSTSSASALYGQPLLLSVPKHKLTLESLYQAVCDRISRYVKQPLPDEFGSSPLEPGACNGSRNSCEGEDEEEMEHQEEGKEQLSETEGSGEDEPGNDPSETTQKKIKGQPCPKRLFTFSLVNSYGTADINSLAADGKLLKLNSRSTLAMDWDRETRRLYYDEQESEAYEKHVSMLQPQKKKKTTVALRDCIELFTTMETLGEHDPWYCPNCKKHQQATKKFDLWSLPKILVVHLKRFSYNRYWRDKLDTVVEFPIRGLNMSEFVCNLSARPYVYDLIAVSNHYGAMGVGHYTAYAKNKLNGKWYYFDDSNVSWPLRIR
  num_certain_transmembrane_segments: 0
  num_found: 3
SWN_PWP1_HUMAN: 
  num_putative_transmembrane_segments: 0
  transmembrane_segments: 
  - aaseq: MGVLFCSSCCPDLPFIYAFGG
    stop: 450
    start: 430
    probability: 21.0
  aaseq: MNRSRQVTCVAWVRCGVAKETPDKVELSKEEVKRLIAEAKEKLQEEGGGSDEEETGSPSEDGMQSARTQARPREPLEDGDPEDDRTLDDDELAEYDLDKYDEEGDPDAETLGESLLGLTVYGSNDQDPYVTLKDTEQYEREDFLIKPSDNLIVCGRAEQDQCNLEVHVYNQEEDSFYVHHDILLSAYPLSVEWLNFDPSPDDSTGNYIAVGNMTPVIEVWDLDIVDSLEPVFTLGSKLSKKKKKKGKKSSSAEGHTDAVLDLSWNKLIRNVLASASADNTVILWDMSLGKPAASLAVHTDKVQTLQFHPFEAQTLISGSYDKSVALYDCRSPDESHRMWRFSGQIERVTWNHFSPCHFLASTDDGFVYNLDARSDKPIFTLNAHNDEISGLDLSSQIKGCLVTASADKYVKIWDILGDRPSLVHSRDMKMGVLFCSSCCPDLPFIYAFGGQKEGLRVWDISTVSSVNEAFGRRERLVLGSARNSSISGPFGSRSSDTPMES
  num_certain_transmembrane_segments: 1
  num_found: 1
SW_FGF7_HUMAN: 
  num_putative_transmembrane_segments: 0
  transmembrane_segments: 
  - aaseq: RSCFHIICLVGTISLACNDMT
    stop: 36
    start: 16
    probability: 21.0
  aaseq: MHKWILTWILPTLLYRSCFHIICLVGTISLACNDMTPEQMATNVNCSSPERHTRSYDYMEGGDIRVRRLFCRTQWYLRIDKRGKVKGTQEMKNNYNIMEIRTVAVGIVAIKGVESEFYLAMNKEGKLYAKKECNEDCNFKELILENHYNTYASAKWTHNGGEMFVALNQKGIPVRGKKTKKEQKTAHFLPMAIT
  num_certain_transmembrane_segments: 1
  num_found: 1
SWN_SM31_HUMAN: 
  aaseq: MSEEKPKEGVKTENDHINLKVAGQDGSVVQFKIKRHTSLSKLMKAYCERQGLSMRQIRFRFDGQPINETDTPAQLRMEDEDTIDVFQQQTGGVPESSLAGHSF
  num_found: 0
SWN_UFD1_HUMAN: 
  aaseq: MFSFNMFDHPIPRVFQNRFSTQYRCFSVSMLAWPNDRSDVEKGGKIIMPPSALDQLSRLNITYPMLFKLTNKNSDRMTHCGVLEFVADEGICYLPHWMMQNLLLEEDGLVQLETVNLQVATYSKSKFCYLPHWMMQNLLLEEGGLVQVESVNLQVATYSKFQPQSADFLDITNPKAVLENALRNFACLTTGDVIAINYNEKIYELRVMETKPDKAVSIHECDMNVDFDAPLGYKEPERQVQHEESTEGEADHSGYAGELGFRAFSGSGNRLDGKKKGVEPSPSPIKPGDIKRGIPNYEFKLGKITFIRNSRPLVKKVEEDEAGGRFVAFSGEGQSLRKKGRKP
  num_found: 0
SWN_UBCE_HUMAN: 
  aaseq: MNSNVENLPPHIIRLVYKEVTTLTADPPDGIKVFPNEEDLTDLQVTIEGPEGTPYAGGLFRMKLLLGKDFPASPPKGYFLTKIFHPNVGANGEICVNVLKRDWTAELGIRHVLLTIKCLLIHPNPESALNEEAGRLLLENYEEYAARARLLTEIHGGAGGPSGRAEAGRALASGTEASSTDPGAPGGPGGAEGPMAKKHAGERDKKLAAKKKTDKKRALRALRRL
  num_found: 0
SWN_K1CL_HUMAN: 
  num_putative_transmembrane_segments: 0
  transmembrane_segments: 
  - aaseq: GSAFGFGASCGGGFSAASMFG
    stop: 64
    start: 44
    probability: 21.0
  - aaseq: ALGGGSFGGLGMGFGGSPGGG
    stop: 108
    start: 88
    probability: 21.0
  aaseq: MDLSNNTMSLSVRTPGLSRRLSSQSVIGRPRGMSASSVGSGYGGSAFGFGASCGGGFSAASMFGSSSGFGGGSGSSMAGGLGAGYGRALGGGSFGGLGMGFGGSPGGGSLGILSGNDGGLLSGSEKETMQNLNDRLASYLDKVRALEEANTELENKIREWYETRGTGTADASQSDYSKYYPLIEDLRNKIISASIGNAQLLLQIDNARLAAEDFRMKYENELALRQGVEADINGLRRVLDELTLTRTDLEMQIESLNEELAYMKKNHEDELQSFRVGGPGEVSVEMDAAPGVDLTRLLNDMRAQYETIAEQNRKDAEAWFIEKSGELRKEISTNTEQLQSSKSEVTDLRRAFQNLEIELQSQLAMKKSLEDSLAEAEGDYCAQLSQVQQLISNLEAQLLQVRADAERQNVDHQRLLNVKARLELEIETYRRLLDGEAQGDGLEESLFVTDSKSQAQSTDSSKDPTKTRKIKTVVQEMVNGEVVSSQVQEIEELM
  num_certain_transmembrane_segments: 2
  num_found: 2
SWN_UBCC_HUMAN: 
  aaseq: MAGLPRRIIKETQRLLAEPVPGIKAEPDESNARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVDKLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKTNEAQAIETARAWTRLYAMNNI
  num_found: 0
SWN_SM32_HUMAN: 
  aaseq: MADEKPKEGVKTENNDHINLKVAGQDGSVVQFKIKRHTPLSKLMKAYCERQGLSMRQIRFRFDGQPINETDTPAQLEMEDEDTIDVFQQQTGGVY
  num_found: 0
END_YAML2

end



